[build]
  publish = "dist/angular20/browser"
  command = "npm run build"

# Redirect root to /home so that landing at the site base goes to the Home route
[[redirects]]
  from = "/"
  to = "/home"
  status = 301
  force = true

[[plugins]]
  package = "@netlify/angular-runtime"
