[build]
  publish = "dist/local-walls/browser"
  command = "npm run build:ssr"

# Redirect root to /home so that landing at the site base goes to the Home route
[functions]
  directory = "dist/local-walls/server"


[[plugins]]
  package = "@netlify/angular-runtime"
