[build]
  publish = "dist/local-walls/browser"
  command = "npm run build:ssr"

[[plugins]]
  package = "@netlify/angular-runtime"
[functions]
  directory = "dist/local-walls/server"
  node_bundler = "esbuild"
