[build]
  publish = "dist/local-walls/browser"
  command = "npm run build"

# Redirect root to /home so that landing at the site base goes to the Home route
[[redirects]]
  from = "/"
  to = "/home"
  status = 301
  force = true

# SSR, all routes must go to Netlify runtime function
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[plugins]]
  package = "@netlify/angular-runtime"
