// Grade model: enum of French sport grades, type alias from enum values,
// and ordered lists for convenience.

export enum GradeEnum {
  Three = '3',
  Four = '4',
  Five = '5',
  FivePlus = '5+',
  SixA = '6a',
  SixAPlus = '6a+',
  SixB = '6b',
  SixBPlus = '6b+',
  SixC = '6c',
  SixCPlus = '6c+',
  SevenA = '7a',
  SevenAPlus = '7a+',
  SevenB = '7b',
  SevenBPlus = '7b+',
  SevenC = '7c',
  SevenCPlus = '7c+',
  EightA = '8a',
  EightAPlus = '8a+',
  EightB = '8b',
  EightBPlus = '8b+',
  EightC = '8c',
  EightCPlus = '8c+',
  NineA = '9a',
  NineAPlus = '9a+',
  NineB = '9b',
  NineBPlus = '9b+',
  NineC = '9c',
}

export type Grade = `${GradeEnum}`;

export const ORDERED_GRADE_VALUES: readonly Grade[] = [
  GradeEnum.Three,
  GradeEnum.Four,
  GradeEnum.Five,
  GradeEnum.FivePlus,
  GradeEnum.SixA,
  GradeEnum.SixAPlus,
  GradeEnum.SixB,
  GradeEnum.SixBPlus,
  GradeEnum.SixC,
  GradeEnum.SixCPlus,
  GradeEnum.SevenA,
  GradeEnum.SevenAPlus,
  GradeEnum.SevenB,
  GradeEnum.SevenBPlus,
  GradeEnum.SevenC,
  GradeEnum.SevenCPlus,
  GradeEnum.EightA,
  GradeEnum.EightAPlus,
  GradeEnum.EightB,
  GradeEnum.EightBPlus,
  GradeEnum.EightC,
  GradeEnum.EightCPlus,
  GradeEnum.NineA,
  GradeEnum.NineAPlus,
  GradeEnum.NineB,
  GradeEnum.NineBPlus,
  GradeEnum.NineC,
] as const;

export type RoutesByGrade = Partial<Record<Grade, number>>;
