#!/usr/bin/env sh

# Run formatter before commit
echo "Running formatter (npm run format) before commit..."
npm run format
RESULT=$?
if [ $RESULT -ne 0 ]; then
  echo "Formatter failed. Commit aborted."
  exit $RESULT
fi

exit 0
